In [1]:
!pip3 install numpy

In [1]:
import numpy as np
a = np.arange(6)
print(a)
print(type(a))
print(a[:])
a2 = a[np.newaxis, :]
print(a2.shape)
print(a.shape)
a = np.array([[1, 2, 3, 4], [5, 6,7, 8], [9, 10, 11, 12]])
print(a[0])
a = np.array([1,2,3])
print(np.zeros(2))
print(np.ones(2))
print(np.empty(2))
print(np.arange(4))
print(np.arange(2, 9, 2))
print(np.linspace(0, 10, num=5))
a=np.ones(2, dtype=np.int64)
print(a)
b = np.array([3,1,2,4,5,6,7,8])
print(b)
b = np.sort(a)
print(b)

[0 1 2 3 4 5]
<class 'numpy.ndarray'>
[0 1 2 3 4 5]
(1, 6)
(6,)
[1 2 3 4]
[0. 0.]
[1. 1.]
[1. 1.]
[0 1 2 3]
[2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]
[1 1]
[3 1 2 4 5 6 7 8]
[1 1]


In [2]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.concatenate((a,b))
print(c)
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
print(np.concatenate((x,y)))
print(x)
print(y)

[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]
[[5 6]]


In [3]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
array_example = np.array([[[0, 1, 2, 3], 
                           [4, 5, 6, 7]],
                          
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])  
array_example.ndim
array_example.size
array_example.shape
a = np.arange(6)
print(a)
b = a.reshape(2,3)
print(b)
c = a.reshape(3,2)
print(c)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]


In [5]:
np.reshape(a, newshape=(1, 6), order='C')
a = np.array([1,2,3,4,5,6])
a.shape
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [6]:
five = (a>=5)
print(a[five])
b= a[a%2==0]
print(b)
c = a[(a>2) & (a<11)]
print(c)

[5 6]
[2 4 6]
[3 4 5 6]


In [7]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
b = np.nonzero(a<5)
print(b)
list_of_coordinates = list(zip(b[0], b[1]))
for coord in list_of_coordinates:
    print(coord)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))
(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [8]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a1 = a[3:8]
a1

array([4, 5, 6, 7, 8])

In [9]:
a1 = np.array([[1, 1],
              [2, 2]])
a2 = np.array([[3, 3],
              [4, 4]])
np.vstack((a1, a2))
np.concatenate((a1, a2), axis=0) 
np.concatenate((a1, a2))
np.concatenate((a1, a2), axis=0)
print(x)
x = np.arange(1, 25).reshape(2, 12)
print(x)
np.hsplit(x,3)
np.hsplit(x, (3, 4))

[[1 2]
 [3 4]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [10]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
print(a[2, :])
print(a[:,2])
b = a[0,:]
print(b)
b[0]=99
print(b)
b2 = a.copy()
print(b2)
b2[1,1] = 7
print(b2)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 9 10 11 12]
[ 3  7 11]
[1 2 3 4]
[99  2  3  4]
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[99  2  3  4]
 [ 5  7  7  8]
 [ 9 10 11 12]]
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
data = np.array([1, 2])
ones = np.ones(2, dtype = int)
print(data + ones)
print(data-ones)
print(data*ones)
print(data/ones)

[2 3]
[0 1]
[1 2]
[1. 2.]


In [12]:
a = np.array([1, 2, 3, 4])
print(sum(a))

10


In [13]:
b = np.array([[1, 1],[2, 2]])
print(b.sum())
print(b.sum(axis=0))
print(b.sum(axis=1))
print(data.max())
print(data.sum())
print(data.min())

6
[3 3]
[2 4]
2
3
1


In [14]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
a.sum()
a.min()
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [15]:
data = np.array([[1, 2], [3, 4], [5, 6]])
print(data)
print(data[0, 1])

[[1 2]
 [3 4]
 [5 6]]
2


In [16]:
data[1:3]
data[0:2, 0]
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [17]:
data = np.array([[1, 2], [5, 3], [4, 6]])
print(data)
print(data.max(axis=0))
print(data.max(axis=1))
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
print(data + ones)

[[1 2]
 [5 3]
 [4 6]]
[5 6]
[2 5 6]
[[2 3]
 [4 5]]


In [18]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
print(data + ones_row)
print(data.reshape(2, 3))
print(data.reshape(3, 2))

[[2 3]
 [4 5]
 [6 7]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [19]:
arr = np.arange(6).reshape((2, 3))
print(arr)
arr.transpose()
print(arr.T)

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


In [20]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
ra = np.flip(arr)
print('Reversed Array: ', ra)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [21]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
ra = np.flip(arr_2d)
rar = np.flip(arr_2d, axis=0)
print(rar)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [22]:
rac = np.flip(arr_2d, axis=1)
print(rac)
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
[[ 1 10  3  4]
 [ 5  6  7  8]
 [ 9  2 11 12]]


In [23]:
a= np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a.flatten() 
a1 = x.flatten()
a1[0] = 99
print(x)
print(a1)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
[99  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [24]:
a2 = x.ravel() 
a2[0] = 98
print(x)
print(a2)

[[98  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
[98  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
